spring.application.name=library-management-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/library_management_db
spring.datasource.username=postgres
spring.datasource.password=an05teodor

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=bXlWZXJ5U5Ryb55nU2VjcmV0S2V5Rm7ySnd0VG9rZW5xMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=86400000

server.port=8081