spring.application.name=library-management-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/library_management_db
spring.datasource.username=postgres
spring.datasource.password=an05teodor

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=bXlWZXJ5U5RYa55nU2VjcmV0S2V5Rm7ySnd0VG9rZW5xMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=86400000

app.security.admin-registration-key=LIBRARY_ADMIN_2026

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.security.reset-code-expiration-minutes=10

# mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# password reset
app.password-reset.code-expiration-minutes=10
app.password-reset.resend-cooldown-seconds=60
app.password-reset.max-attempts=5
app.password-reset.from-email=${MAIL_FROM:${MAIL_USERNAME}}

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=8082